apiVersion: v1
kind: PersistentVolume
metadata:
  name: conda-store-environments
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/hostpath-provisioner/conda-store/conda-store-worker-environments
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  claimRef:
    namespace: conda-store
    name: conda-store-worker-claim