apiVersion: v1
kind: PersistentVolume
metadata:
  name: conda-store-environments
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: /tmp/mnt-vol-kub
  claimRef:
    namespace: conda-store
    name: conda-store-worker-claim
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube