Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  # forces to use $HOME/.vagrant.d/insecure_private_key' we need the
  # ssh key to be the same when /home get mounted on nfs
  config.ssh.insert_key = false

  config.vm.define "conda-store-test", primary: true do |vm01|
    vm01.vm.hostname = "conda-store-test"
    vm01.vm.provider "libvirt" do |libvirtvm01|
      libvirtvm01.memory = 2048
      libvirtvm01.cpus = 2
    end
  end

  # issues with dnssec and https://github.com/lavabit/robox/issues/106
  config.vm.provision 'shell', inline: "if grep 'DNSSEC=yes' /etc/systemd/resolved.conf; then sed -i 's/DNSSEC=yes/DNSSEC=no/g' /etc/systemd/resolved.conf; systemctl restart systemd-resolved.service; fi", privileged: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.groups = {
      "conda-store" => ["conda-store-test"],
    }
  end
end
