"""add_celery_table

Revision ID: 97d2ad3d29f4
Revises: 6d477abab205
Create Date: 2023-02-01 16:38:41.273465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d2ad3d29f4'
down_revision = '6d477abab205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
