"""on delete cascade policy

Revision ID: e5abc533f920
Revises: 16f65805dc8f
Create Date: 2023-05-03 11:32:52.785859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5abc533f920'
down_revision = '16f65805dc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('build_artifact_build_id_fkey', 'build_artifact', type_='foreignkey')
    op.create_foreign_key('build_artifact_build_id_fkey', 'build_artifact', 'build', ['build_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('build_artifact_build_id_fkey', 'build_artifact', type_='foreignkey')
    op.create_foreign_key('build_artifact_build_id_fkey', 'build_artifact', 'build', ['build_id'], ['id'])
    # ### end Alembic commands ###
