name: "Setup Docker"
description: "Setup tasks needed to build and publish Docker images"

inputs:
  docker-image:
    description: "conda-store project to build the Docker image for: conda-store or conda-store-server"
    required: true
outputs:
  cs-version:
    description: "conda-store current version - dirty tag"
    value: ${{ steps.get-dev-version.outputs.cs-version }}

runs:
  using: "composite"
  steps:
    - name: "Get dev version 🏷️"
      id: get-dev-version
      shell: bash
      run: |
        echo "cs-version=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: "Get project's default Python version 🏷️"
      shell: bash
      run: |
        echo "PYTHON_VERSION_DEFAULT=$(cat .python-version-default)" >> $GITHUB_ENV

    - name: "Lint Dockerfiles 🔍"
      uses: jbergstroem/hadolint-gh-action@v1
      with:
        dockerfile: ${{ inputs.docker-image }}/Dockerfile
        output_format: tty
        error_level: 0

    - name: "Set up Docker Buildx 🏗"
      uses: docker/setup-buildx-action@v3

    - name: "Copy .dockerignore"
      run: |
        cp .dockerignore ${{ inputs.docker-image }}/.dockerignore
      shell: bash
