# This environment file should only be used to build conda-store Docker images
# for development and purpose only - these images are built through GitHub actions
name: conda-store
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nb_conda_kernels
  - nodejs=18
  - yarn
  - constructor # Runtime dependency, but must be conda-installed
