"""Add Environment.description

Revision ID: 8d63a091aff8
Revises: 48be4072fe58
Create Date: 2022-07-15 14:22:00.351131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d63a091aff8'
down_revision = '48be4072fe58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('description', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'description')
    # ### end Alembic commands ###
