// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'community'}],

  // Manual sidebar template
  /*
  tutorialSidebar: [
    'introduction',
    'get-started',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorials/authentication'],
    },
  ],
   */
};

module.exports = sidebars;
