// Copyright (c) conda-store development team. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{ type: "autogenerated", dirName: "community" }],

	// Manual sidebar template
	/*
  tutorialSidebar: [
    'introduction',
    'get-started',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorials/authentication'],
    },
  ],
   */
};

module.exports = sidebars;
