apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "condaStore.fullname" . }}-api-server"
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ include "condaStore.chart" . }}
    app.kubernetes.io/name: {{ include "condaStore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: "{{ template "condaStore.fullname" . }}-api-server"
spec:
  replicas: {{ .Values.apiServer.replicas }}
  selector:
    matchLabels:
      app: "{{ template "condaStore.fullname" . }}-api-server"
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "condaStore.chart" . }}
        app.kubernetes.io/name: {{ include "condaStore.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app: "{{ template "condaStore.fullname" . }}-api-server"
    spec:
      containers:
        - name: "{{ template "condaStore.fullname" . }}-api-server"
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          args:
            - "conda-store-server"
            - "--config"
            - "/etc/conda-store/conda_store_config.py"
          ports:
            - containerPort: {{ .Values.apiServer.port }}
          volumeMounts:
            - name: config
              mountPath: "/etc/conda-store/"
              readOnly: true
            - name: secret
              mountPath: "/var/lib/conda-store"
              readOnly: true
            - name: home
              mountPath: "/home/conda"
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: "{{ template "condaStore.fullname" . }}"
        - name: secret
          secret:
            secretName: {{ .Values.global.condaStoreConfigSecretsName }}
        - name: home
          emptyDir:
            sizeLimit: 1Mi
