apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "condaStore.fullname" . }}-api-server"
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ include "condaStore.chart" . }}
    app.kubernetes.io/name: {{ include "condaStore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: "{{ template "condaStore.fullname" . }}-api-server"
spec:
  replicas: {{ .Values.apiServer.replicas }}
  selector:
    matchLabels:
      app: "{{ template "condaStore.fullname" . }}-api-server"
  template:
    metadata:re
      labels:
        helm.sh/chart: {{ include "condaStore.chart" . }}
        app.kubernetes.io/name: {{ include "condaStore.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app: "{{ template "condaStore.fullname" . }}-api-server"
    spec:
      containers:
        - name: "{{ template "condaStore.fullname" . }}-api-server"
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          args:
            - "conda-store-server"
            - "--config"
            - "/etc/conda-store/conda_store_config.py"
          ports:
            - containerPort: {{ .Values.apiServer.port }}
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conda-store-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conda-store-postgres-secret
                  key: password
            - name: MINIO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conda-store-minio-secret
                  key: username
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conda-store-minio-secret
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conda-store-redis-secret
                  key: password
          volumeMounts:
            - name: config
              mountPath: "/etc/conda-store/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: "{{ template "condaStore.fullname" . }}-api-server"
