podAnnotations: {}
podLabels: {}

global:
  namespace: conda-store
  condaStoreConfig: |
    import logging

    from conda_store_server.server.auth import DummyAuthentication
    from conda_store_server.storage import S3Storage


    c.CondaStore.storage_class = S3Storage
    c.CondaStore.store_directory = "/opt/conda-store/conda-store/"
    c.CondaStore.default_uid = 1000
    c.CondaStore.default_gid = 100
    c.CondaStore.default_permissions = "555"
    c.CondaStoreServer.address = "0.0.0.0"
    c.CondaStoreServer.port = 8080
    c.CondaStoreServer.url_prefix = "/"
    c.CondaStoreServer.authentication_class = DummyAuthentication
    c.CondaStoreWorker.watch_paths = ["/opt/environments"]
    c.CondaStore.environment_directory = "/home/conda/{namespace}/envs/{namespace}-{name}"
  condaStoreConfigSecretsName: conda-store-secret

server:
  nodePort: 30500
  port: 8080
  replicas: 1
  image:
    repository: quansight/conda-store-server
    pullPolicy: IfNotPresent
    tag: 2024.6.1

worker:
  port: 8080
  replicas: 1
  image:
    repository: quansight/conda-store-server
    pullPolicy: IfNotPresent
    tag: 2024.6.1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
