name: "Build PyPI package"

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "conda-store-server/**"
      - "tests/**"
  push:
    branches:
      - main

env:
  FORCE_COLOR: "1" # Make tools pretty.

permissions:
  contents: read # This is required for actions/checkout

jobs:
  # Always build & verify package.
  build-package:
    name: "Build & verify package"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: conda-store-server
    steps:
      - name: "Checkout Repository 🛎"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo "Running on conda-store-server"

      - name: "Build and check package - conda-store-server 📦"
        uses: hynek/build-and-inspect-python-package@v2
        id: baipp
        with:
          path: conda-store-server
          upload-name-suffix: "-conda-store-server"

      - run: echo Packages can be found at ${{ steps.baipp.outputs.dist }} and in artifact ${{ steps.baipp.outputs.artifact-name }}
