name: Documentation

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  build-docs:
    name: 'Build and Test Documentation'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Dependencies
        working-directory: conda-store-server
        run: |
          pip install .[dev]
      - name: Build Documentation
        working-directory: docs
        run: |
          sphinx-build -b html . _build
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/_build
