apiVersion: v1
kind: Service
metadata:
  name: conda-store-server
spec:
  type: NodePort
  ports:
    - name: "8080"
      nodePort: 30500
      port: 8080
      targetPort: 8080
  selector:
    app: conda-store-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conda-store-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conda-store-server
  template:
    metadata:
      labels:
        app: conda-store-server
    spec:
      containers:
        - name: conda-store-server
          image: quansight/conda-store-server:v0.4.5
          args:
            - "conda-store-server"
            - "--config"
            - "/etc/conda-store/conda_store_config.py"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/etc/conda-store/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: conda-store-config
